config/routes.rb
Book::Application.routes.draw do
  
  
  
  
  resources :reviews
  resources :bookdata
  resources :user_sessions
  resources :users
    
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  get "bookdata/:id/reviews", to: 'bookdata#reviews'
  get "users/:id/reviews", to: 'users#books'

  root :to => 'top#index'
  
  

  

end

app/models/bookdatum.rb
class Bookdatum < ActiveRecord::Base
  has_many :reviews
  has_many :users, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :bookdatum
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  authenticates_with_sorcery!

  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  
  has_many :reviews
  has_many :bookdata, :through => :reviews, :uniq => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :require_login
  protect_from_forgery with: :exception
  
  protected
  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end

end

app/controllers/bookdata_controller.rb
class BookdataController < ApplicationController
  before_action :set_bookdatum, only: [:show, :edit, :update, :destroy]

  # GET /bookdata
  # GET /bookdata.json
  def index
    @bookdata = Bookdatum.all
  end

  # GET /bookdata/1
  # GET /bookdata/1.json
  def show
  end

  # GET /bookdata/new
  def new
    @bookdatum = Bookdatum.new
  end

  # GET /bookdata/1/edit
  def edit
  end

  # GET /bookdata/1/reviews
  def reviews
    @reviews = Review.find_all_by_bookdatum_id(params[:id])
  end

  # POST /bookdata
  # POST /bookdata.json
  def create
    @bookdatum = Bookdatum.new(bookdatum_params)

    respond_to do |format|
      if @bookdatum.save
        format.html { redirect_to @bookdatum, notice: 'Bookdatum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookdatum }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookdata/1
  # PATCH/PUT /bookdata/1.json
  def update
    respond_to do |format|
      if @bookdatum.update(bookdatum_params)
        format.html { redirect_to @bookdatum, notice: 'Bookdatum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookdata/1
  # DELETE /bookdata/1.json
  def destroy
    @bookdatum.destroy
    respond_to do |format|
      format.html { redirect_to bookdata_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookdatum
      @bookdatum = Bookdatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookdatum_params
      params.require(:bookdatum).permit(:title, :authors, :price, :published)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @bookdata = Bookdatum.all
  end

  # GET /reviews/1/edit
  def edit
    @bookdata = Bookdatum.all
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:bookdatum_id, :user_id, :body)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_filter :require_login
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  skip_before_filter :require_login, :except => [:destroy]

  
  def new
    @user = User.new
  end
  
  def create
    respond_to do |format|
      if @user = login(params[:username],params[:password])
        format.html { redirect_back_or_to(:users, :notice => 'Login successful.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
    
  def destroy
    logout
    redirect_to(:users, :notice => 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, :only => [:index, :new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1/books
  def books
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:users, :notice => 'User was successfully created.') }
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
#      params.require(:user).permit(:username, :email, :crypted_password, :salt)
      params.require(:user).permit(:username, :email, :password, :password_confirmation )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookdata_helper.rb
module BookdataHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookdata/_form.html.erb
<%= form_for(@bookdatum) do |f| %>
  <% if @bookdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookdatum.errors.count, "error") %> prohibited this bookdatum from being saved:</h2>

      <ul>
      <% @bookdatum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookdata/edit.html.erb
<h1>Editing bookdatum</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookdatum %> |
<%= link_to 'Back', bookdata_path %>

app/views/bookdata/index.html.erb
<h1>Listing books</h1>

<table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Authors</th>
      <th>Price</th>
      <th>Published</th>
      <th>Management</th>
    </tr>
  </thead>

  <tbody>
    <% @bookdata.each do |bookdatum| %>
      <tr>
        <td><%= bookdatum.title %></td>
        <td><%= bookdatum.authors %></td>
        <td><%= bookdatum.price %></td>
        <td><%= bookdatum.published %></td>
        <td><%= link_to 'Reviews', { :action => 'reviews', :id => bookdatum.id} %>
            <%= link_to 'Show', bookdatum %>
            <%= link_to 'Edit', edit_bookdatum_path(bookdatum) %>
            <%= link_to 'Destroy', bookdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New book', new_bookdatum_path %>
<br>
<%= link_to "Home", { :controller => 'top', :action => 'index'} %>

app/views/bookdata/new.html.erb
<h1>New bookdatum</h1>

<%= render 'form' %>

<%= link_to 'Back', bookdata_path %>

app/views/bookdata/reviews.html.erb
<h1>reviews</h1>

<table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>Date</th>
      <th>Reviewer</th>
      <th>Review</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.updated_at %></td>
        <td><%= review.user.username %></td>
        <td><%= review.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', bookdata_path %>
<br>
<%= link_to "Home", { :controller => 'top', :action => 'index'} %>

app/views/bookdata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookdatum.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @bookdatum.authors %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bookdatum.price %>
</p>

<p>
  <strong>Published:</strong>
  <%= @bookdatum.published %>
</p>


<%= link_to 'Edit', edit_bookdatum_path(@bookdatum) %> |
<%= link_to 'Back', bookdata_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Book" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fuid-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">BookData</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user %>
                <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
                <li><%= link_to "Logout", :logout %></li>
              <% else %>
                <li><%= link_to "Register", new_user_path %> |</li>
                <li><%= link_to "Login", :login %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
          <div>
            <p id="notice"><%= notice %></p>
            <p id="alert"><%= alert %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Data</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Menu</li>
                  <li><%= link_to "Books", bookdata_path %></li>
                  <li><%= link_to "Reviews", reviews_path %></li>
                  <li><%= link_to "Users", users_path %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bookdatum_id %><br>
    <%= f.collection_select(:bookdatum_id, @bookdata, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, { :cols => 40, :rows => 20} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>BookTitle</th>
      <th>User</th>
      <th>Body</th>
      <th>Management</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.bookdatum.title %></td>
        <td><%= review.user.username %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %>
            <%= link_to 'Edit', edit_review_path(review) %>
            <%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>
<br>
<%= link_to "Home", { :controller => 'top', :action => 'index'} %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookdata:</strong>
  <%= @review.bookdatum.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/top/index.html.erb
<h1>BookData Top</h1>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :username %><br />
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/books.html.erb
<h1>books</h1>

<table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @user.bookdata.each do |book| %>
      <tr>
        <td><%= book.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', users_path %>
<br>
<%= link_to "Home", { :controller => 'top', :action => 'index'} %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Management</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Books', { :action => 'books', :id => user.id} %>
            <%= link_to 'Show', user %>
            <%= link_to 'Edit', edit_user_path(user) %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br>
<%= link_to "Home", { :controller => 'top', :action => 'index'} %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

 <table class="table table-striped table-bordered" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Review</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @user.reviews.each do |review| %>
      <tr>
        <td><%= review.bookdatum.title %></td>
        <td><%= review.body %></td>
        <td><%= review.updated_at %></td><br>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>